### ISSUE TITLE
Checklist for v0.2.0

### ISSUE THREAD

**Issue by ahwillia** [ahwillia/Einsum.jl#8]
I have had a mental checklist of things to implement. All of this should be doable in the near-term / mid-term for the next release:
- [x] Add docs for `@einsimd`
- [x] Support for inplace operations
  - [x] Initial PR https://github.com/ahwillia/Einsum.jl/pull/7
  - [x] Docs added
- [x] Support for offsets in indices, https://github.com/ahwillia/Einsum.jl/issues/6, https://github.com/ahwillia/Einsum.jl/pull/12
  - [ ] with constants, `@einsum y[i] = y[i+3]`
  - [ ] with variables,  `@einsum y[i] = y[i+offset]`
- [x] More flexible operations in the inner loop. (Below are some minimal examples)
  - [x] `@einsum y[i] = 2*y[i]`
  - [x] `@einsum x[i] = x[i] + 5`

**Comment by ahwillia** [comment]
Also steal any ideas from @dfdx here: https://github.com/dfdx/Espresso.jl/blob/tensor-diff/src/einstein.jl

**Comment by phipsgabler** [comment]
- Would you agree to bumping the `REQUIRE`d Julia version to 0.6? Since 0.5 seems already outdated nowadays... and also, we're only testing for >= 0.6.
- Is the offset support already completed?
- In the long run (given I find the time), I would like to replace the "escaping" of external variables as symbols by using interpolation syntax, like `A[i, $(f(j))]`. It [kind of works](https://github.com/phipsgabler/Einsum.jl/blob/175545ece297a626be625193258236aff6b01e1a/test/runtests.jl) already. That, IMO, would be both more consistent with other "splice-capable" macros, and more flexible. What do you think?

**Comment by ahwillia** [comment]
> Would you agree to bumping the REQUIREd Julia version to 0.6? Since 0.5 seems already outdated nowadays... and also, we're only testing for >= 0.6.

Done.
